<?php


return [

    'Admin Login' => '1',
    'Manage User' => '2',
    'Manage Role' => '3',
    'Department' => '4',
    'Task Stage' => '5',
    'Photo Print Setting' => '6',
    'Employee' => '7',
    'Task Duration' => '8',
    'Expected Delivery Days' => '9',
    'Variant Type' => '10',
    'Gst Percentage' => '11',
    'Shipped Vendor' => '12',
    'Coupon Code' => '13',
    'Category' => '14',
    'Ticket' => '15',
    'Cms Banner' => '16',
    'Cms Video' => '17',
    'Cms Greeting' => '18',
    'Contest' => '19',
    'Other District' => '20',
    'Delivery charge' => '21',
    'Passport Size Photo' => '22',
    'Photo Print' => '23',
    'Photo Frame' => '24',
    'Personalized Products' => '25',
    'Ecommerce Products'  => '26',
    'Selfie Album' => '27',
    'Customer' => '28',
    'Employee Login' => '29',
    'Task Manager' => '30',
    'Management Communication' => '31',
    'Refund' => '32',
    'Logout' => '33',
    'Waiting COD' => '34',
    'Waiting Payments' => '35',
    'Waiting Dispatch' => '36',
    'Delivery Details' => '37',
    'Ratings & Review' => '38',
    'Terms and conditions' => '39',
    'Delivery Management' => '40',
    'Enquiry' => '41',
    'Quote' => '42',
    'Pg Link Generate' => '43',
    'Create Order' => '44',
];